# Generated by Django 5.2.4 on 2025-07-29 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0017_alter_wallet_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alert',
            new_name='Withdrawalert',
        ),
        migrations.RemoveField(
            model_name='alert2',
            name='user',
        ),
        migrations.CreateModel(
            name='Generalalert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('alert', models.CharField(choices=[('sweetAlert', 'click on to show'), ('paid', 'mark as paid')], default='sweetAlert', max_length=24)),
                ('status', models.CharField(choices=[('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info'), ('KYC has not been uploaded kindly fill in your details on your kyc data table', 'KYC has not been uploaded kindly fill in your details on your kyc data table'), ('Dear Investor we are writing to inform you that recent transfer to our institution hasbeen subject to a Cost of Transfer C O T fee As you may be aware C O T fee are charged by intermediary banks of cover the costs of processing international transactions.', 'Dear Investor we are writing to inform you that recent transfer to our institution hasbeen subject to a Cost of Transfer C O T fee As you may be aware C O T fee are charged by intermediary banks of cover the costs of processing international transactions.'), ('We hope this message finds you well This is to inform you today regarding your outstanding teaching fee . As you know investing in education is one of the best decisions you can make for your future. Our teaching program is designed to provide you with the knowledge and skills necessary to succeed in your chosen field.', 'We hope this message finds you well This is to inform you today regarding your outstanding teaching fee . As you know investing in education is one of the best decisions you can make for your future. Our teaching program is designed to provide you with the knowledge and skills necessary to succeed in your chosen field.'), ('We regret to inform you that we are unable to confirm your recent withdrawal request at this time. Upon reviewing your request, we have discovered that your bank does not support the total amount you are attempting to withdraw from your investment account to your bank account.', 'We regret to inform you that we are unable to confirm your recent withdrawal request at this time. Upon reviewing your request, we have discovered that your bank does not support the total amount you are attempting to withdraw from your investment account to your bank account.'), ('Please kindly Purchase a higher signal to be able to make any withdraw due to the amount your signal is too low', 'Please kindly Purchase a higher signal to be able to make any withdraw due to the amount your signal is too low'), ('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info'), ('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info'), ('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info'), ('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info'), ('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info'), ('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info')], default='Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info.', max_length=7000, null=True)),
                ('kyc', models.CharField(choices=[('swal-2', 'swal-2'), ('swal-4', 'swal-4')], default='#swal-4', max_length=24)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Alert1',
        ),
        migrations.DeleteModel(
            name='Alert2',
        ),
    ]
