# Generated by Django 5.2.4 on 2025-07-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0018_rename_alert_withdrawalert_remove_alert2_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalalert',
            name='alert',
            field=models.CharField(choices=[('sweetAlert', 'ON'), ('OFF', 'OFF')], default='sweetAlert', max_length=24),
        ),
    ]
