# Generated by Django 5.2.4 on 2025-07-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0019_alter_generalalert_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalalert',
            name='kyc',
        ),
        migrations.AlterField(
            model_name='generalalert',
            name='alert',
            field=models.CharField(choices=[('sweetAlert', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=24),
        ),
    ]
