# Generated by Django 5.2.4 on 2025-07-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0021_alter_generalalert_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='accountnumber',
            new_name='account_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='iban',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='swift_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
