# Generated by Django 5.2.4 on 2025-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0022_rename_accountnumber_transaction_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='upgrade_status',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Elite', 'Elite'), ('Exclusive', 'Exclusive')], default='Silver', max_length=200, null=True),
        ),
    ]
