# Generated by Django 5.2.4 on 2025-07-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0023_deposit_upgrade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='active_deposit',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
